name: CI/CD – Build & Deploy

on:
  push:
    branches:
      - master   # ou la branche que tu utilises en prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'   # à adapter selon ton projet

      # 3. Installer les dépendances et builder le site
      - name: Install & Build
        run: |
          npm ci
          npm run build

      # 4. Se connecter en SSH et déployer
      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/sitepro"